USE master;
ALTER DATABASE QLLT SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
DROP DATABASE QLLT; -- Thêm DROP để xóa DB cũ nếu cần
CREATE DATABASE QLLT;
USE QLLT;

--------------------------- TẠO BẢNG ------------------------------
CREATE TABLE [PRODUCT] (
    [id_product] INTEGER NOT NULL IDENTITY UNIQUE,
    [name] NVARCHAR(100) NOT NULL,
    [cpu] VARCHAR(50) NOT NULL,
    [ram] VARCHAR(20) NOT NULL,
    [rom] VARCHAR(20) NOT NULL,
    [graphics_card] VARCHAR(50) NOT NULL,
    [battery] VARCHAR(20) NOT NULL,
    [weight] VARCHAR(10) NOT NULL,
    [price] DECIMAL NOT NULL,
    [quantity] INTEGER NOT NULL DEFAULT 0,
    [quantity_stock] INTEGER NOT NULL DEFAULT 0,
    [id_category] INTEGER NOT NULL,
    [id_company] INTEGER NOT NULL,
    [img] VARCHAR(255) NOT NULL,
    [size_screen] VARCHAR(20) NOT NULL,
    [operating_system] VARCHAR(50) NOT NULL,
    [status] INTEGER NOT NULL,
    PRIMARY KEY([id_product])
);
GO

-- Tạo bảng CATEGORY
CREATE TABLE [CATEGORY] (
    [id_category] INTEGER NOT NULL IDENTITY UNIQUE,
    [name_category] NVARCHAR(100) NOT NULL,
    [status] INTEGER NOT NULL,
    PRIMARY KEY([id_category])
);
GO

-- Tạo bảng COMPANY
CREATE TABLE [COMPANY] (
    [id_company] INTEGER NOT NULL IDENTITY UNIQUE,
    [name_company] NVARCHAR(100) NOT NULL,
    [address] NVARCHAR(255) NOT NULL,
    [contact] VARCHAR(20) NOT NULL,
    [status] INTEGER NOT NULL,
    PRIMARY KEY([id_company])
);
GO

-- Tạo bảng CUSTOMER
CREATE TABLE [CUSTOMER] (
    [id_customer] INTEGER NOT NULL IDENTITY UNIQUE,
    [name] NVARCHAR(50) NOT NULL,
    [gender] NVARCHAR(10) NOT NULL,
    [birthdate] DATE NOT NULL,         -- Ngày sinh
    [citizen_id] VARCHAR(20) NOT NULL, -- Số CCCD
    [contact] VARCHAR(20) NOT NULL,
    [status] INTEGER NOT NULL,
    PRIMARY KEY([id_customer])
);
GO

-- Tạo bảng BILL_EXPORT
CREATE TABLE [BILL_EXPORT] (
    [id_bill_ex] INTEGER NOT NULL IDENTITY UNIQUE,
    [id_admin] INTEGER NOT NULL,
    [id_customer] INTEGER NULL,
    [total_product] INTEGER NOT NULL,
    [total_price] DECIMAL NOT NULL,
    [status] INTEGER NOT NULL,
    [date_ex] DATETIME NOT NULL,  -- Thêm cột ngày xuất
    PRIMARY KEY([id_bill_ex])
);
GO

-- Tạo bảng BILL_EXPORT_DETAIL
CREATE TABLE [BILL_EXPORT_DETAIL] (
    [id_bill_ex] INTEGER NOT NULL,
    [id_product] INTEGER NOT NULL,
    [num_seri] VARCHAR(50) NOT NULL,
    [unit_price] DECIMAL NOT NULL,
    PRIMARY KEY([id_bill_ex], [id_product], [num_seri])
);
GO

-- Tạo bảng SERI_PRODUCT
CREATE TABLE [SERI_PRODUCT] (
    [num_seri] VARCHAR(50) NOT NULL UNIQUE,
    [id_product] INTEGER NOT NULL,
    [status] INTEGER NOT NULL,
    PRIMARY KEY([num_seri])
);
GO

-- Tạo bảng BILL_IMPORT
CREATE TABLE [BILL_IMPORT] (
    [id_bill_im] INTEGER NOT NULL IDENTITY UNIQUE,
    [id_admin] INTEGER NOT NULL,
    [id_product] INTEGER NOT NULL,
    [unit_price] DECIMAL NOT NULL,
    [total_price] DECIMAL NOT NULL,
    [quantity] INTEGER NOT NULL,
    [date_import] DATETIME NOT NULL,
    PRIMARY KEY([id_bill_im])
);
GO

-- Tạo bảng ADMIN
CREATE TABLE [ADMIN] (
    [id_admin] INTEGER NOT NULL IDENTITY UNIQUE,
	[id_role] INTEGER NOT NULL,
    [name] NVARCHAR(50) NOT NULL,
    [gender] NVARCHAR(10) NOT NULL,
    [email] VARCHAR(100) NOT NULL,
    [contact] VARCHAR(20) NOT NULL,
    [password] VARCHAR(50) NOT NULL,
    [status] INTEGER NOT NULL,
    PRIMARY KEY([id_admin])
);
GO

-- Tạo bảng INSURANCE
CREATE TABLE [INSURANCE] (
    [id_insurance] INTEGER NOT NULL IDENTITY UNIQUE,
    [id_admin] INTEGER NOT NULL,
    [id_customer] INTEGER NOT NULL,
    [id_product] INTEGER NOT NULL,
    [num_seri] VARCHAR(50) NOT NULL,
    [start_date] DATETIME NOT NULL,
    [end_date] DATETIME NOT NULL,
    [description] NVARCHAR(255) NULL,
    PRIMARY KEY ([id_insurance])
);
GO

-- Tạo bảng INSURANCE_CLAIM
CREATE TABLE [INSURANCE_CLAIM] (
    [id_claim] INTEGER NOT NULL IDENTITY UNIQUE,
    [id_insurance] INTEGER NOT NULL,
    [id_admin] INTEGER NOT NULL,
    [id_product] INTEGER NOT NULL,
    [num_seri] VARCHAR(50) NOT NULL,
    [description] NVARCHAR(255) NOT NULL,
    [date_processed] DATETIME NOT NULL DEFAULT GETDATE(),
    [status] NVARCHAR(50) NOT NULL,
    PRIMARY KEY ([id_claim])
);
GO


-- Tạo bảng ROLE
CREATE TABLE [ROLE] (
	[id_role] INTEGER NOT NULL IDENTITY UNIQUE,
	[name_role] NVARCHAR(50) NOT NULL,
	[status] INTEGER NOT NULL,
	 PRIMARY KEY([id_role])
);
GO
-- Tạo bảng AUTHORITIES
CREATE TABLE [AUTHORITIES] (
	[id_role] INTEGER NOT NULL,
	[id_authorities] INTEGER NOT NULL ,
	[name_authorities] NVARCHAR(150) NOT NULL,
	[status] INTEGER NOT NULL,
	 PRIMARY KEY([id_role],[id_authorities])
);
GO

CREATE TABLE [AUTHORITIES_DETAIL] (
	[id_role] INTEGER NOT NULL,
	[id_authorities] INTEGER NOT NULL ,
	[id_detail] INTEGER NOT NULL ,
	[name] NVARCHAR(150) NOT NULL,
	[status] INTEGER NOT NULL,
	 PRIMARY KEY([id_role],[id_authorities],[id_detail])
);
GO
-- Ràng buộc khóa ngoại
ALTER TABLE [PRODUCT]
ADD CONSTRAINT FK_PRODUCT_CATEGORY
    FOREIGN KEY ([id_category]) REFERENCES [CATEGORY]([id_category])
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
GO
ALTER TABLE [ADMIN]
ADD CONSTRAINT FK_ADMIN_ROLE
    FOREIGN KEY ([id_role]) REFERENCES [ROLE]([id_role])
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
GO
ALTER TABLE [AUTHORITIES]
ADD CONSTRAINT FK_AUTHORITIES_ROLE
    FOREIGN KEY ([id_role]) REFERENCES [ROLE]([id_role])
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
GO
ALTER TABLE AUTHORITIES_DETAIL
ADD CONSTRAINT FK_AUTHORITIES_DETAIL_AUTHORITIES
    FOREIGN KEY (id_role, id_authorities)
    REFERENCES AUTHORITIES(id_role, id_authorities);
GO
ALTER TABLE [PRODUCT]
ADD CONSTRAINT FK_PRODUCT_COMPANY
    FOREIGN KEY ([id_company]) REFERENCES [COMPANY]([id_company])
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
GO

ALTER TABLE [SERI_PRODUCT]
ADD CONSTRAINT FK_SERI_PRODUCT_PRODUCT
    FOREIGN KEY ([id_product]) REFERENCES [PRODUCT]([id_product])
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
GO

ALTER TABLE [BILL_IMPORT]
ADD CONSTRAINT FK_BILL_IMPORT_ADMIN
    FOREIGN KEY ([id_admin]) REFERENCES [ADMIN]([id_admin])
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
GO

ALTER TABLE [BILL_IMPORT]
ADD CONSTRAINT FK_BILL_IMPORT_PRODUCT
    FOREIGN KEY ([id_product]) REFERENCES [PRODUCT]([id_product])
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
GO

ALTER TABLE [BILL_EXPORT]
ADD CONSTRAINT FK_BILL_EXPORT_ADMIN
    FOREIGN KEY ([id_admin]) REFERENCES [ADMIN]([id_admin])
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
GO

ALTER TABLE [BILL_EXPORT]
ADD CONSTRAINT FK_BILL_EXPORT_CUSTOMER
    FOREIGN KEY ([id_customer]) REFERENCES [CUSTOMER]([id_customer])
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
GO

ALTER TABLE [BILL_EXPORT_DETAIL]
ADD CONSTRAINT FK_BILL_EXPORT_DETAIL_BILL_EXPORT
    FOREIGN KEY ([id_bill_ex]) REFERENCES [BILL_EXPORT]([id_bill_ex])
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
GO

ALTER TABLE [BILL_EXPORT_DETAIL]
ADD CONSTRAINT FK_BILL_EXPORT_DETAIL_PRODUCT
    FOREIGN KEY ([id_product]) REFERENCES [PRODUCT]([id_product])
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
GO

ALTER TABLE [BILL_EXPORT_DETAIL]
ADD CONSTRAINT FK_BILL_EXPORT_DETAIL_SERI
    FOREIGN KEY ([num_seri]) REFERENCES [SERI_PRODUCT]([num_seri])
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
GO

ALTER TABLE [INSURANCE]
ADD CONSTRAINT FK_INSURANCE_ADMIN
    FOREIGN KEY ([id_admin]) REFERENCES [ADMIN]([id_admin])
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
GO

ALTER TABLE [INSURANCE]
ADD CONSTRAINT FK_INSURANCE_CUSTOMER
    FOREIGN KEY ([id_customer]) REFERENCES [CUSTOMER]([id_customer])
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
GO

ALTER TABLE [INSURANCE]
ADD CONSTRAINT FK_INSURANCE_PRODUCT
    FOREIGN KEY ([id_product]) REFERENCES [PRODUCT]([id_product])
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
GO

ALTER TABLE [INSURANCE]
ADD CONSTRAINT FK_INSURANCE_SERI
    FOREIGN KEY ([num_seri]) REFERENCES [SERI_PRODUCT]([num_seri])
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
GO

ALTER TABLE [INSURANCE_CLAIM]
ADD CONSTRAINT FK_INSURANCE_CLAIM_INSURANCE
    FOREIGN KEY ([id_insurance]) REFERENCES [INSURANCE]([id_insurance])
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
GO

ALTER TABLE [INSURANCE_CLAIM]
ADD CONSTRAINT FK_INSURANCE_CLAIM_ADMIN
    FOREIGN KEY ([id_admin]) REFERENCES [ADMIN]([id_admin])
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
GO

ALTER TABLE [INSURANCE_CLAIM]
ADD CONSTRAINT FK_INSURANCE_CLAIM_PRODUCT
    FOREIGN KEY ([id_product]) REFERENCES [PRODUCT]([id_product])
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
GO

ALTER TABLE [INSURANCE_CLAIM]
ADD CONSTRAINT FK_INSURANCE_CLAIM_SERI
    FOREIGN KEY ([num_seri]) REFERENCES [SERI_PRODUCT]([num_seri])
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
GO